import type { ToolGroup } from "@/components/tools/ToolsIndexList";

/**
 * Single source of truth for the /tools hub's grouping — also powers the
 * header "Calculators" dropdown, so the two never drift.
 */
export const CALCULATOR_GROUPS: ToolGroup[] = [
  {
    label: "Plan for today",
    calculators: [
      {
        href: "/tools/salary",
        icon: "💰",
        title: "Salary & Pay Hub",
        description: "Take-home pay, 50/25/25 budget split, payday routing, KRA tax shield, and salary negotiation — all from one gross salary.",
        insight: "≈37% of a Ksh 100,000 gross goes to deductions before you see a shilling. Model every angle here.",
        isNew: true,
      },
      {
        href: "/tools/savings-goal",
        icon: "🎯",
        title: "Savings Goal Calculator",
        description: "Work out how much to save each month to hit a target amount.",
        insight: "Small, consistent amounts beat big, irregular ones.",
      },
      {
        href: "/tools/hustle-smoother",
        icon: "🔄",
        title: "Hustle Income Smoother",
        description: "Turn months of variable freelance or informal income into a steady, reliable monthly salary.",
        insight: "Enter your last 3–12 months' earnings, get the safe draw and buffer fund needed to ride out lean months.",
        isNew: true,
      },
      {
        href: "/tools/20th-challenge",
        icon: "🔥",
        title: "20th-to-20th Savings Challenge",
        description: "Commit to saving a fixed amount every month and build an unbroken streak with monthly check-ins.",
        insight: "6 months is the habit-formation threshold. Check in between the 15th and 25th — the app keeps score.",
        isNew: true,
      },
      {
        href: "/tools/loan-repayment",
        icon: "🏦",
        title: "Loan / HELB Repayment Calculator",
        description: "See your monthly installment and total interest on any loan.",
        insight: "A SACCO loan can cost a third of what a mobile lender charges for the same amount.",
      },
    ],
  },
  {
    label: "Plan for the future",
    calculators: [
      {
        href: "/tools/investment-returns",
        icon: "📈",
        title: "Investment Returns Calculator",
        description: "Project how a lump sum plus monthly contributions grows over time.",
        insight: "Compounding grows your money fastest in the later years — start now.",
      },
      {
        href: "/tools/fire-number",
        icon: "🔥",
        title: "FIRE Number Calculator",
        description: "Your Kenya-localized retirement number: 20× expenses, inflation-adjusted to your retirement year.",
        insight: "Kenya's high MMF/bond yields support a 5% withdrawal rate — 20× expenses, not the Western 25×.",
      },
      {
        href: "/tools/dhowcsd",
        icon: "🏦",
        title: "DhowCSD T-Bill Ladder",
        description: "Split capital across 91/182/364-day Treasury Bills for quarterly liquidity.",
        insight: "The blended ladder yield nearly triples what a bank savings account pays.",
        isNew: true,
      },
      {
        href: "/tools/money-runway",
        icon: "⏳",
        title: "Money Runway Calculator",
        description: "See how long your savings will last at a given monthly withdrawal.",
        insight: "A modest return can make your savings last years longer.",
      },
      {
        href: "/planners/education",
        icon: "🏫",
        title: "School Fees Sinking Fund Smoother",
        description: "Turn three termly fee shocks into one flat monthly deposit that earns its own subsidy.",
        insight: "An MMF's interest quietly pays ~12% of your annual fees for you — free school uniforms.",
        isNew: true,
      },
      {
        href: "/tools/education-savings",
        icon: "🎓",
        title: "Kids' Education Savings Calculator",
        description: "Plan monthly savings for Junior and Senior Secondary fees, CBC-aware.",
        insight: "CBC's 6-year secondary system means two fee step-ups, not one — plan for both.",
      },
    ],
  },
  {
    label: "Debt & protection",
    calculators: [
      {
        href: "/tools/debt-escape",
        icon: "💸",
        title: "Debt Stack Buster",
        description: "Enter your Fuliza, Tala, and mobile loans. The avalanche plan shows you the fastest, cheapest way to clear every shilling.",
        insight: "Fuliza at 32%/month is the costliest debt most Kenyans carry — tackle it first.",
        isNew: true,
      },
      {
        href: "/tools/sha-health",
        icon: "🏥",
        title: "SHA Health Coverage Gap",
        description: "See your exact SHIF contribution and the top-up cost needed to access private hospitals, dental, and optical.",
        insight: "SHA covers public facilities only — know what it misses before you need it.",
        isNew: true,
      },
      {
        href: "/tools/land-purchase",
        icon: "🏡",
        title: "Land Purchase True Cost",
        description: "The quoted plot price is only the start. See stamp duty, legal fees, valuation, title transfer, and survey costs before you sign.",
        insight: "Transaction fees add 8–12% on top of the quoted price — budget this before negotiating.",
        isNew: true,
      },
    ],
  },
  {
    label: "Pesa realities",
    calculators: [
      {
        href: "/tools/sacco-vs-bank",
        icon: "⚖️",
        title: "SACCO vs Bank Loan Comparison",
        description: "Compare SACCO, bank, and mobile lender costs for the same loan.",
        insight: "Most Kenyans don't realise how much cheaper SACCO loans are.",
        isNew: true,
      },
      {
        href: "/tools/inflation-reality",
        icon: "📉",
        title: "Inflation Reality Calculator",
        description: "See what your salary will really be worth in the future.",
        insight: "Kenya CPI has averaged 6.5% per year — your salary needs to keep pace.",
        isNew: true,
      },
      {
        href: "/tools/kplc-optimizer",
        icon: "⚡",
        title: "KPLC Token Band Optimizer",
        description: "Split your monthly token budget into two buys and gain free units on the same spend.",
        insight: "Two half-month purchases keep you in the lower tariff band — same money, more kWh.",
        isNew: true,
      },
      {
        href: "/tools/fuliza-cost",
        icon: "📱",
        title: "True Cost of Fuliza Calculator",
        description: "Find out what Fuliza really costs before you borrow.",
        insight: "Fuliza costs ~400% APR — more than a payday lender.",
        isNew: true,
      },
      {
        href: "/tools/guarantor-shield",
        icon: "🎯",
        title: "Sacco Guarantor Liability Shield",
        description: "See how much of your 3× borrowing power is frozen by loans you've guaranteed.",
        insight: "Guarantee half your deposits away and your development loan gets slashed — check before you apply.",
        isNew: true,
      },
      {
        href: "/tools/one-third-rule",
        icon: "⚠️",
        title: "1/3 Rule Checker",
        description: "Check if your SACCO and loan deductions are legally compliant.",
        insight: "Many Kenyans unknowingly have illegal deductions taken from their pay.",
        isNew: true,
      },
      {
        href: "/tools/chama",
        icon: "🤝",
        title: "Chama / Group Savings Optimizer",
        description: "Simulate merry-go-round payouts, welfare fund size, or group investment returns over 1–5 years.",
        insight: "11.4 million Kenyans save through chamas — model yours before the next meeting.",
        isNew: true,
      },
    ],
  },
];
